### ISSUE TITLE
[Bug]: Workflow skips subreddit that contains string from previous subreddit

### ISSUE THREAD

**Issue by ghost** [chrisgrieser/alfred-reddit-browser#1]
### Bug Description

Workflow incorrectly skips subreddit when its name contains a substring of the previously opened subreddit, causing it to open the next subreddit in the configuration list instead.

### To Reproduce

1. Add "chatgpt" and "chatgptpro" subreddits to workflow configuration (one after the other)
2. Open "chatgpt" subreddit in workflow
3. Use command-enter to open next workflow. "chatgptpro" should open, but the workflow opens the subreddit after "chatgptpro", according to the list in the workflow configuration

### Debugging Log

```Text
N/A
```

### Workflow Configuration

![image](https://github.com/user-attachments/assets/4ccb7cf8-c0cc-4650-a99f-cabedf02ee3f)

### Checklist

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/alfred-reddit-browser/releases/latest) of this workflow.
- [X] I am using Alfred 5. (Older versions are not supported anymore.)

**Comment by chrisgrieser** [comment]
Huh, you found exactly the one edge case I haven't considered. Thx, just fixed it.

Available in the Alfred Gallery in 1-2 days, or directly by downloading the latest release here: https://github.com/chrisgrieser/alfred-reddit-browser/releases/download/1.6.3/alfred-reddit-browser.alfredworkflow
